# To configure the doctring coverage hook
paths:
  - library/RAVE/src/RAVE
exclude: .*/(__init__|face_detection/detectors/models)
verbose: 3
skip_file_doc: True
skip_init: True
skip_private: True
skip_magic: True
fail_under: 75