# File with general configs used for running AudioManager

# Microphone geometries
mic_dict : {    # RAVE mic dict
    'mics': {
      '0': [ -0.07055, 0, 0 ],
      '1': [ -0.07055, 0.0381, 0 ],
      '2': [ -0.05715, 0.0618, 0 ],
      '3': [ -0.01905, 0.0618, 0 ],
      '4': [ 0.01905, 0.0618, 0 ],
      '5': [ 0.05715, 0.0618, 0 ],
      '6': [ 0.07055, 0.0381, 0 ],
      '7': [ 0.07055, 0, 0 ]
    },
    'nb_of_channels': 8
}
mic_dict_respeaker: {     # ReSpeaker mic dict
    'mics': {
      '0': [0.02285, 0.02285, 0],
      '1': [-0.02285, 0.02285, 0],
      '2': [-0.02285, -0.02285, 0],
      '3': [0.02285, -0.02285, 0]
    },
    'nb_of_channels': 4
}

# Output
default_output_dir: '.'
output_stereo: True

# Arguments
use_beamformer: False
use_groundtruth: True   # Calculate various ground truths
print_specs: False       # Print spectrograms


## Jetson configs
# Jetson mic source  (default idx uses default device)
jetson_source: {
    'name': 'JetsonMic',
    'type': 'mic',
    'idx': '4'
}
# Jetson playback sink (default idx uses default device)
jetson_sink: {
    'name': 'JetsonPlayback',
    'type': 'play',
    'idx': 'default'
}


## PC configs
# Sinks  (default/null idx uses default device)
sinks: [
#    {
#        'name': 'playback1',
#        'type': 'play',
#        'idx': 'default'
#    },
    {
        'name': 'original',
        'type': 'sim',
        'beamform': False
    },
    {
        'name': 'output',
        'type': 'sim',
        'beamform': True
    },
    {
        'name': 'speech_out',
        'type': 'sim',
        'beamform': False
    },
    {
        'name': 'noise_out',
        'type': 'sim',
        'beamform': False
    },
    {
        'name': 'output_gt',
        'type': 'sim',
        'beamform': True
    }
]
