# File with general configs used for running AudioManager

# Chunk size for fourier transform
chunk_size: 256

# MicArray
 mic_dict : {
     'mics': {
         '0': [-0.1, -0.1, 0],
         '1': [-0.1, 0.1, 0],
         '2': [0.1, -0.1, 0],
         '3': [0.1, 0.1, 0]
     },
     'nb_of_channels': 4
 }

# Beamformer to use
beamformer: 'mvdr'

# Output channels (mono vs stereo)
out_channels: 2
