# File with general configs used for running AudioManager

# Chunk size for fourier transform
chunk_size: 256

# RAVE mic dict
mic_dict : {
    'mics': {
      '0': [ -0.07055, 0, 0 ],
      '1': [ -0.07055, 0.0381, 0 ],
      '2': [ -0.05715, 0.0618, 0 ],
      '3': [ -0.01905, 0.0618, 0 ],
      '4': [ 0.01905, 0.0618, 0 ],
      '5': [ 0.05715, 0.0618, 0 ],
      '6': [ 0.07055, 0.0381, 0 ],
      '7': [ 0.07055, 0, 0 ]
    },
    'nb_of_channels': 8
}

# ReSpeaker mic dict
#mic_dict: {
#    'mics': {
#      '0': [0.02285, 0.02285, 0],
#      '1': [-0.02285, 0.02285, 0],
#      '2': [-0.02285, -0.02285, 0],
#      '3': [0.02285, -0.02285, 0]
#    },
#    'nb_of_channels': 4
#}

# Thomas mic dict
#mic_dict : {
#    'mics': {
#         '0': [3.308, 6.47, 3.239],
#         '1': [3.305, 6.467, 3.285],
#         '2': [3.323, 6.5, 3.312],
#         '3': [3.345, 6.536, 3.293],
#         '4': [3.349, 6.539, 3.247],
#         '5': [3.330, 6.506, 3.220]
#    },
#    'nb_of_channels': 6
#}

# Beamformer to use
beamformer: 'mvdr'

# Output channels
out_channels: 1

# Jetson configs
# Jetson mic source  (default idx uses default device)
jetson_source: {
    'name': 'JetsonMic',
    'type': 'mic',
    'idx': '4'
}
# Jetson playback sink (default idx uses default device)
jetson_sink: {
    'name': 'JetsonPlayback',
    'type': 'play',
    'idx': 'default'
}
