# File with individual configs used for running AudioManager (DO NOT VERSION IN GIT)

# Chunk size for fourier transform
default_output_dir: 'C:\GitProjet\pipeline'

# Device index for microphone array
mic_array_index: 0

# Sources  (default idx uses default device)
#source: {
#    'name': 'Mic1',
#    'type': 'mic',
#    'idx': null
#}
source: {
    'name': 'sim1',
    'type': 'sim',
    'file': 'C:\\GitProjet\\MS-SNSD\\output\\2\\clnsp0_AirConditioner_2_Babble_8\\audio.wav'
}

# Sinks  (default idx uses default device)
# For every sink added, have to add a check and data to ouput in location in the code
sinks: [
#    {
#        'name': 'playback1',
#        'type': 'play',
#        'idx': 'default'
#    },
    {
        'name': 'original',
        'type': 'sim'
#        'file': 'C:\\GitProjet\\MS-SNSD\\output\\2\\clnsp0_AirConditioner_2_Babble_8\\audio.wav'
    },
    {
        'name': 'output',
        'type': 'sim'
#       'file': 'C:\\GitProjet\\MS-SNSD\\output\\2\\clnsp0_AirConditioner_2_Babble_8\\audio.wav'
    }
]