# File with general configs used for running AudioManager

# Chunk size for fourier transform
chunk_size: 256

# MicArray
mic_dict : {
    'mics': {
         '0': [-0.001905, 0.00643, 0],
         '1': [0.001905, 0.00643, 0],
         '2': [-0.005715, 0.00643, 0],
         '3': [0.005715, 0.00643, 0],
         '4': [-0.007355, 0.00381, 0],
         '5': [0.007355, 0.00381, 0],
         '6': [-0.007355, 0, 0],
         '7': [0.007355, 0, 0]
    },
    'nb_of_channels': 8
}

# Beamformer to use
beamformer: 'mvdr'

# Output channels (mono vs stereo)
out_channels: 8

# Jetson configs
# Jetson mic source  (default idx uses default device)
jetson_source: {
    'name': 'JetsonMic',
    'type': 'mic',
    'idx': 'default'
}
# Jetson playback sink (default idx uses default device)
jetson_sink: {
    'name': 'JetsonPlayback',
    'type': 'play',
    'idx': 'default'
}
