# Randomized configs to use for dataset generation

# List of various room dimensions
# Shape [x, y, z] ([left-right, front-back, up-down])
room: [[10, 10, 10], [20, 20, 20], [30, 30, 30]]

# Path to folder containing source files
source_folder: "/Users/felixducharmeturcotte/Documents/MS-SNSD/clean_train"

# Path to folder containing noise files
noise_folder: "/Users/felixducharmeturcotte/Documents/MS-SNSD/noise_train"

# Range of noises count to add to audio file
noise_count_range: [1, 1]

# Whether to use speech as noise sources
speech_as_noise: False

# Number of samples to get per speech source
sample_per_speech: 5

# Data split to use for [train, val, test]
data_split: [0.7, 0.15, 0.15]
